export const GET_PRODUCTS_LIST_REQUEST = "@products/GET_PRODUCTS_LIST_REQUEST";
export const GET_PRODUCTS_LIST_SUCCESS = "@products/GET_PRODUCTS_LIST_SUCCESS";
export const GET_PRODUCTS_LIST_FAILURE = "@products/GET_PRODUCTS_LIST_FAILURE";
